<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('properties')->insert([
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Parramatta', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Ryde', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Ryde', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Ryde', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Ryde', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Ryde', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Castle Hill', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'NSW', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Southbank', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'O\'Sullivan Beach', 'state' => 'Qld', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Geelong', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Fitzroy', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Richmond', 'state' => 'Vic', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia'],
            ['updated_at'=> date('Y-m-d H:i:s'), 'created_at' => date('Y-m-d H:i:s'), 'guid' =>\Uuid::generate(4)->string, 'suburb' => 'Subiaco', 'state' => 'WA', 'country' => 'Australia'],
        ]);
    }
}
